/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fiu.bookingapp.page;

import fiu.bookingapp.models.Schedule;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author User
 */
public class ManageSchedulesFrame extends javax.swing.JFrame {
    private JTable table;
    private JTextField txtDate, txtTime;
    private JButton btnAdd, btnRefresh;
    /**
     * Creates new form ManageSchedulesFrame
     */
    public ManageSchedulesFrame() {
        initComponents();
        setTitle("Manage Schedules");
        setSize(600, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
        setLocationRelativeTo(null);

        // Table
        table = new JTable();
        JScrollPane sp = new JScrollPane(table);
        sp.setBounds(20, 20, 540, 200);
        add(sp);

        // Label & Input
        JLabel lblDate = new JLabel("Date (YYYY-MM-DD):");
        lblDate.setBounds(20, 240, 140, 25);
        add(lblDate);

        txtDate = new JTextField();
        txtDate.setBounds(160, 240, 120, 25);
        add(txtDate);

        JLabel lblTime = new JLabel("Time (HH:MM:SS):");
        lblTime.setBounds(300, 240, 120, 25);
        add(lblTime);

        txtTime = new JTextField();
        txtTime.setBounds(420, 240, 100, 25);
        add(txtTime);

        // Buttons
        btnAdd = new JButton("Add Schedule");
        btnAdd.setBounds(160, 280, 140, 30);
        add(btnAdd);

        btnRefresh = new JButton("Refresh");
        btnRefresh.setBounds(320, 280, 120, 30);
        add(btnRefresh);

        // Events
        btnAdd.addActionListener(e -> addSchedule());
        btnRefresh.addActionListener(e -> loadSchedules());

        // Initial Load
        loadSchedules();
    }

    private void loadSchedules() {
        List<Schedule> list = Schedule.getAllSchedules();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Date", "Time", "Available"});
        for (Schedule s : list) {
            model.addRow(new Object[]{
                s.getId(), s.getDate(), s.getTimeSlot(), s.isAvailable() ? "Yes" : "No"
            });
        }
        table.setModel(model);
    }
    
    private void addSchedule() {
        String date = txtDate.getText().trim();
        String time = txtTime.getText().trim();

        boolean success = Schedule.insertSchedule(date, time);
        if (success) {
            JOptionPane.showMessageDialog(this, "Schedule added!");
            txtDate.setText("");
            txtTime.setText("");
            loadSchedules();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add schedule!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageSchedulesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageSchedulesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageSchedulesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageSchedulesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageSchedulesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
