/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fiu.bookingapp.page;

import fiu.bookingapp.models.Service;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageServiceFrame extends javax.swing.JFrame {

    JTable table;
    JButton btnRefresh;
    private JTextField txtName, txtPrice, txtDuration;
    private JButton btnAdd;
    
    private void loadServiceData() {
        List<Service> services = Service.getAllServices();
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"ID", "Name", "Price", "Duration (min)"});
        for (Service s : services) {
            model.addRow(new Object[]{
                s.getId(), s.getName(), s.getPrice(), s.getDuration()
            });
        }
        table.setModel(model);
    }
    
    public ManageServiceFrame() {
        initComponents();
        setTitle("Manage Services");
        setSize(700, 500);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(null);

        // === Table ===
        table = new JTable();
        JScrollPane sp = new JScrollPane(table);
        sp.setBounds(20, 20, 640, 250);
        add(sp);

        // === Label & Input ===
        JLabel lblName = new JLabel("Name:");
        lblName.setBounds(20, 290, 50, 25);
        add(lblName);

        txtName = new JTextField();
        txtName.setBounds(80, 290, 150, 25);
        add(txtName);

        JLabel lblPrice = new JLabel("Price:");
        lblPrice.setBounds(250, 290, 50, 25);
        add(lblPrice);

        txtPrice = new JTextField();
        txtPrice.setBounds(300, 290, 100, 25);
        add(txtPrice);

        JLabel lblDuration = new JLabel("Duration:");
        lblDuration.setBounds(420, 290, 70, 25);
        add(lblDuration);

        txtDuration = new JTextField("menit");
        txtDuration.setBounds(490, 290, 80, 25);
        add(txtDuration);

        // === Button Add ===
        btnAdd = new JButton("Add Service");
        btnAdd.setBounds(580, 290, 120, 25);
        add(btnAdd);

        // === Button Refresh ===
        btnRefresh = new JButton("Refresh");
        btnRefresh.setBounds(580, 330, 120, 25);
        add(btnRefresh);

        // === Action Listeners ===
        btnAdd.addActionListener(e -> addService());
        btnRefresh.addActionListener(e -> loadServiceData());

        // Initial Load
        loadServiceData();
    }
    
    private void addService() {
        try {
            String name = txtName.getText().trim();
            double price = Double.parseDouble(txtPrice.getText().trim());
            int duration = Integer.parseInt(txtDuration.getText().trim());

            boolean success = Service.insertService(name, price, duration);
            if (success) {
                JOptionPane.showMessageDialog(this, "Service added successfully!");
                loadServiceData();
                txtName.setText("");
                txtPrice.setText("");
                txtDuration.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add service.");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Input error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageServiceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageServiceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
